services:
  - type: web
    name: cybercore-panel
    runtime: python
    region: ohio
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: PORT
        value: 7860
